141 prototype configuration
daphne-eu/daphne pull request #336
Opened 2022-04-06 20:36 UTC by matejmoravec

2022-04-07 17:34 UTC, pdamme requested changes
Thanks @matejmoravec for re-opening the PR (#324) in your own name after the migration from GitLab.

Unfortunately, it looks like the additional merge commit you added undid some of my finalizing changes, which made the code ready for integration. For instance, `DaphneUserConfig.h` uses `"GSS"` as the default task partitioning scheme again, and the example config files from the test case, which I had moved to another directory, have re-appeared in their former place... **But no worries, this can easily be fixed**. Please remove your merge commit by executing the following in your local repository:

```bash
# go back to my finalizing commit
git reset --hard 69fe6528d552d3ed0ceaa664dda3fba8ff6cd42c
git push origin HEAD --force
```

Furthermore, I've just edited your PR such that it requests integration into `daphne-eu:main` (instead of `daphne-eu:141-prototype-configuration`).

2022-04-08 11:13 UTC, matejmoravec commented
> Thanks @matejmoravec for re-opening the PR (#324) in your own name after the migration from GitLab.
> 
> Unfortunately, it looks like the additional merge commit you added undid some of my finalizing changes, which made the code ready for integration. For instance, `DaphneUserConfig.h` uses `"GSS"` as the default task partitioning scheme again, and the example config files from the test case, which I had moved to another directory, have re-appeared in their former place... **But no worries, this can easily be fixed**. Please remove your merge commit by executing the following in your local repository:
> 
> ```shell
> # go back to my finalizing commit
> git reset --hard 69fe6528d552d3ed0ceaa664dda3fba8ff6cd42c
> git push origin HEAD --force
> ```
> 
> Furthermore, I've just edited your PR such that it requests integration into `daphne-eu:main` (instead of `daphne-eu:141-prototype-configuration`).

Thank you,  @pdamme , for your review. I did what you suggested, and I hope PR is now ready to be merged. I'm sorry for my mistakes, and I will be more careful next time.

2022-04-26 12:44 UTC, pdamme approved these changes

2022-04-26 12:47 UTC, merged

2022-04-26 12:49 UTC, pdamme commented
Thanks, @matejmoravec. Looks good now. I've just merged it in.