Hdfs support
daphne-eu/daphne pull request #767
Opened 2024-06-26 20:09 UTC by aristotelis96

This PR introduces support for Hadoop Distributed File System (HDFS).

- Added dependency libhdfs3 (Native C/C++ HDFS Client)
- Updated container.
- Kernels for reading and writing to HDFS in Daphne binary format and csv format.
- Distributed kernels to support parallel read/write for the distributed runtime (only synchronous gRPC for now).
- Added cli arguments (and updated config file).

2024-06-28 15:11 UTC, corepointer commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/thirdparty/installed/include/hdfs)
This line should fail in the docker environment where dependencies are installed in /usr/local

2024-09-09 22:02 UTC, corepointer requested changes
This feature is looking good in general. A few things could be improved (see code comments). I did not test-run the code but tried compilation of the dependencies to check support in the Docker images. 
Please make the integration optional like CUDA or MPI.

2024-09-10 15:36 UTC, aristotelis96 commented
Thank you for the valuable feedback @corepointer. I will address the comments and make HDFS build optional. 👍

2024-09-16 19:51 UTC, aristotelis96 commented
Thank you @corepointer again for your review. I've added an optional `--hdfs` build argument similar to CUDA and MPI.

2024-09-18 18:47 UTC, closed without merging

2024-09-18 18:53 UTC, corepointer commented
LGTM - thx for your contribution @aristotelis96 @psomas @KostasBitsakos 

I had to fix a few things to make everything compile and squashed into two commits for dependencies and feature.
The changes for the Docker scripts should have gone to main before merging the PR - this is why these changes now show up as part of the PR. The final result is the same, just the presented changes here might be confusing.

2024-09-18 18:58 UTC, corepointer commented
Test cases would be nice ;-)
I could imagine an automated setup of a mini single-node cluster that reads from localhost [1].
Might be a nice student project :D

[1] https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html